config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:show]
  resources :skills, only: [:show]

  root "users#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/proficiency.rb
class Proficiency < ApplicationRecord
  belongs_to :user
  belongs_to :skill

  validates :level, presence: true, inclusion: -1...5
end

app/models/skill.rb
class Skill < ApplicationRecord
    has_many :proficiencies
    has_many :skills, through: :proficiencies
    validates :name, uniqueness: true, presence:true, length: {maximum: 20}

end

app/models/user.rb
class User < ApplicationRecord
    has_many :proficiencies
    has_many :skills, through: :proficiencies
    validates :name, presence: true, uniqueness: true, length: {maximum: 20}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
    def show 
        @skill =  Skill.find(params[:id])
        @not_found = true unless @skill
        @proficiencies = @skill.proficiencies.select{|skill| skill.level > -1} if @skill
        @users = @proficiencies.map{|p| p.user}
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id]||1)

        @not_found =  true unless @user
        if @user
            @proficiencies =  @user.proficiencies 
            @master = []
            @proficient = []
            @competent = []
            @novice = []
            @interested = []
            @not_interested = []
            @proficiencies.each do |skill|
                case skill.level
                when 4 
                    @master.push(skill)
                when 3 
                    @proficient.push(skill)
                when 2 
                    @competent.push(skill)
                when 1 
                    @novice.push(skill)
                when 0 
                    @interested.push(skill)
                when -1 
                    @not_interested.push(skill)
                end
            end
        end

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UserSkills</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/skills/show.html.erb
<div class="container">
    <%if @not_found%>
        <h2>Skill not found</h2>
    <% else %>

        <%=link_to "Back", :back, class:"back"%>
        <h2>Users interested in <span class="item"> <%= @skill.name %> </span> </h2>

        <div class="users">
        <%@users.each do |user|%>
            <%=link_to user.name, user_path(id: user.id), class: "user item"%>
        <%end%>
        </div>
    <% end %>
</div>

app/views/users/show.html.erb
    <div class="container">
        <img class="image" alt="user" src="https://upload.wikimedia.org/wikipedia/commons/8/89/Portrait_Placeholder.png">
        <h2><%=@user.name%></h2>
        <div class="skills">
            <%unless @master.length === 0%>
                <h3>Master/Influencer</h3>
                <ul class="category">
                    <%@master.each do |skill|%>
                        <li class="item"><%=link_to skill.skill_name, skill_path(skill.skill_id) %></li>
                    <%end%>
                </ul>
            <%end%>
            <%unless @proficient.length === 0%>
                <h3>Proficient</h3>
                <ul class="category">
                    <%@proficient.each do |skill|%>
                        <li class="item"><%=link_to skill.skill_name, skill_path(skill.skill_id) %></li>
                    <%end%>
                </ul>
            <%end%>
            <%unless @competent.length === 0%>
                <h3>Competent</h3>
                <ul class="category">
                    <%@competent.each do |skill|%>
                        <li class="item"><%=link_to skill.skill_name, skill_path(skill.skill_id) %></li>
                    <%end%>
                </ul>
            <%end%>
            <%unless @novice.length === 0%>
                <h3>Novice</h3>
                <ul class="category">
                    <%@novice.each do |skill|%>
                        <li class="item"><%=link_to skill.skill_name, skill_path(skill.skill_id) %></li>
                    <%end%>
                </ul>
            <%end%>
            <%unless @interested.length === 0%>
                <h3>Not competent but interested</h3>
                <ul class="category">
                    <%@interested.each do |skill|%>
                        <li class="item"><%=link_to skill.skill_name, skill_path(skill.skill_id) %></li>
                    <%end%>
                </ul>
            <%end%>
            
        </div>
    </div>